#!/bin/bash
rm -rf /tmp/menu
wget -O /tmp/menu.zip "https://raw.githubusercontent.com/myzid/vvip/main/menu/project.zip" >/dev/null 2>&1
    mkdir /tmp/menu
    7z e -pFadlyvpnprojek213 /tmp/menu.zip -o/tmp/menu/ >/dev/null 2>&1
    chmod +x /tmp/menu/*
    mv /tmp/menu/* /usr/sbin/
rm -rf /root/menu/*
rm -rf /root/menu
rm -rf menu.zip
rm -rf update.sh
clear
menu
